baseurl      = "https://rlemaitre.com"
title        = "Raphaël Lemaitre"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "Developer – Architect — Engineering Manager – CTO"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you linke
    enableSharingButtons = true

    # Metadata mostly used in document's head
    description = "Raphaël Lemaitre's website and blog."
    keywords = "homepage, blog"
    images = ["/images/screenshot.png"]

    [params.portrait]
    path = "/images/rlemaitre.jpeg"

    [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/rlemaitre"

    [[params.social]]
    name = "github"
    url  = "https://github.com/rlemaitre"

    [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/rlemaitre"

    [[params.social]]
    name = "linkedin"
    url  = "https://linkedin.com/in/rlemaitre/"

    #[[params.social]]
    #name = "dev"
    #url  = "https://dev.to/rlemaitre/"
    #
    #[params.social]
    #name = "medium"
    #url  = "https://medium.com/@rlemaitre/"

[languages]
    [languages.en]
        title = "Raphaël Lemaitre"

        [languages.en.params]
            subtitle = "Developer – Architect – Engineering Manager – CTO"
            homeSubtitle = "Developer – Architect – Engineering Manager – CTO"
            keywords = "developer,architect,engineering manager,CTO"
            copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
            readOtherPosts = "Read other posts"
            [languages.en.params.logo]
            logoText = "cd ~"
            logoHomeLink = "/"
            # or
            #
            # path = "/img/your-example-logo.svg"
            # alt = "Your example logo alt text"

        [languages.en.menu]
            [[languages.en.menu.main]]
            identifier = "whoami"
            name       = "whoami"
            url        = "/whoami/"
            weight     = 1
            [[languages.en.menu.main]]
            identifier = "blog"
            name       = "Blog"
            url        = "/posts/"
            weight     = 2

    [languages.fr]
        title = "Raphaël Lemaitre"

        [languages.fr.params]
            subtitle = "Développeur – Architecte – Engineering Manager – CTO"
            homeSubtitle = "Développeur – Architecte – Engineering Manager – CTO"
            keywords = "developpeur,architecte,engineering manager,CTO"
            copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
            readOtherPosts = "Autres posts"
            [languages.fr.params.logo]
            logoText = "cd ~"
            logoHomeLink = "/"
            # or
            #
            # path = "/img/your-example-logo.svg"
            # alt = "Your example logo alt text"

        [languages.fr.menu]
            [[languages.fr.menu.main]]
            identifier = "whoami"
            name       = "whoami"
            url        = "/whoami/"
            weight     = 1
            [[languages.fr.menu.main]]
            identifier = "blog"
            name       = "Blog"
            url        = "/posts/"
            weight     = 2

